USE [master]
GO

CREATE DATABASE [LoggingDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LoggingDatabase', FILENAME = N'E:\MSSQL\DATA\LoggingDatabase.mdf' , SIZE = 104512KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LoggingDatabase_log', FILENAME = N'D:\MSSQL\DATA\LoggingDatabase_log.ldf' , SIZE = 26128KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LoggingDatabase] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LoggingDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LoggingDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LoggingDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LoggingDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LoggingDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LoggingDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [LoggingDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LoggingDatabase] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LoggingDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LoggingDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LoggingDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LoggingDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LoggingDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LoggingDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LoggingDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LoggingDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LoggingDatabase] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LoggingDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LoggingDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LoggingDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LoggingDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LoggingDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LoggingDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LoggingDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LoggingDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LoggingDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [LoggingDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LoggingDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LoggingDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LoggingDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [LoggingDatabase] SET  READ_WRITE 
GO


